test_tests_2015: test_tests_2015_Day_01 $\
                 test_tests_2015_Day_02 $\
                 test_tests_2015_Day_03 $\
                 test_tests_2015_Day_05 $\
                 test_tests_2015_Day_06 $\
                 test_tests_2015_Day_08 $\
                 test_tests_2015_Day_10

include test/tests/_2015/Day_01/makefile
include test/tests/_2015/Day_02/makefile
include test/tests/_2015/Day_03/makefile
include test/tests/_2015/Day_05/makefile
include test/tests/_2015/Day_06/makefile
include test/tests/_2015/Day_08/makefile
include test/tests/_2015/Day_10/makefile