source_2015: source_2015_Day_01 $\
             source_2015_Day_02 $\
             source_2015_Day_03 $\
             source_2015_Day_05 $\
             source_2015_Day_06 $\
             source_2015_Day_08 $\
             source_2015_Day_10

include source/_2015/Day_01/makefile
include source/_2015/Day_02/makefile
include source/_2015/Day_03/makefile
include source/_2015/Day_05/makefile
include source/_2015/Day_06/makefile
include source/_2015/Day_08/makefile
include source/_2015/Day_10/makefile

build/library/source/2015: | build/library/source
	mkdir "$@"